export const USER_FORM_SET_VALUE: "USER_FORM_SET_VALUE" = "USER_FORM_SET_VALUE";

export const GET_REGISTRATION_REQUEST: "GET_REGISTRATION_REQUEST" =
  "GET_REGISTRATION_REQUEST";
export const GET_REGISTRATION_SUCCESS: "GET_REGISTRATION_SUCCESS" =
  "GET_REGISTRATION_SUCCESS";
export const GET_REGISTRATION_FAILED: "GET_REGISTRATION_FAILED" =
  "GET_REGISTRATION_FAILED";

export const GET_LOGIN_REQUEST: "GET_LOGIN_REQUEST" = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS: "GET_LOGIN_SUCCESS" = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILED: "GET_LOGIN_FAILED" = "GET_LOGIN_FAILED";

export const GET_FORGOT_PASS_REQUEST: "GET_FORGOT_PASS_REQUEST" =
  "GET_FORGOT_PASS_REQUEST";
export const GET_FORGOT_PASS_SUCCESS: "GET_FORGOT_PASS_SUCCESS" =
  "GET_FORGOT_PASS_SUCCESS";
export const GET_FORGOT_PASS_FAILED: "GET_FORGOT_PASS_FAILED" =
  "GET_FORGOT_PASS_FAILED";

export const GET_RESET_PASS_REQUEST: "GET_RESET_PASS_REQUEST" =
  "GET_RESET_PASS_REQUEST";
export const GET_RESET_PASS_SUCCESS: "GET_RESET_PASS_SUCCESS" =
  "GET_RESET_PASS_SUCCESS";
export const GET_RESET_PASS_FAILED: "GET_RESET_PASS_FAILED" =
  "GET_RESET_PASS_FAILED";

export const GET_AUTH_REQUEST: "GET_AUTH_REQUEST" = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS: "GET_AUTH_SUCCESS" = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILED: "GET_AUTH_FAILED" = "GET_AUTH_FAILED";

export const GET_LOGOUT_REQUEST: "GET_LOGOUT_REQUEST" = "GET_LOGOUT_REQUEST";
export const GET_LOGOUT_SUCCESS: "GET_LOGOUT_SUCCESS" = "GET_LOGOUT_SUCCESS";
export const GET_LOGOUT_FAILED: "GET_LOGOUT_FAILED" = "GET_LOGOUT_FAILED";

export const GET_UPDATE_USER_REQUEST: "GET_UPDATE_USER_REQUEST" =
  "GET_UPDATE_USER_REQUEST";
export const GET_UPDATE_USER_SUCCESS: "GET_UPDATE_USER_SUCCESS" =
  "GET_UPDATE_USER_SUCCESS";
export const GET_UPDATE_USER_FAILED: "GET_UPDATE_USER_FAILED" =
  "GET_UPDATE_USER_FAILED";

export const CLEAR_REQUESTS_MESSAGE: "CLEAR_REQUESTS_MESSAGE" =
  "CLEAR_REQUESTS_MESSAGE";
